FLASK_NAME= app
FLASK_ENV = development 
SQLALCHEMY_DATABASE_URI = sqlite:///properypulse.db
CLOUDINARY_CLOUD_NAME=dyngpmwvu
CLOUDINARY_API_KEY=734658141928393
CLOUDINARY_API_SECRET=Zl1s5QYtFyRZlTwOf1qI2gDalIQ